"""Compact Russian HTML renderer for JSON reports."""

from __future__ import annotations

import html
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .i18n import normalize_locale


def _text(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "да" if value else "нет"
    if isinstance(value, (dict, list)):
        return str(value)
    return str(value)


def _safe_name(target: str) -> str:
    value = re.sub(r"[^A-Za-z0-9._-]+", "_", target).strip("._")
    return value or "report"


def report_path(report: dict[str, Any], output_dir: str | Path = "reports") -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    return Path(output_dir) / f"{_safe_name(str(report.get('target', 'report')))}_{timestamp}.html"


def _row(label: str, value: Any) -> str:
    return f"<div class=\"row\"><span>{html.escape(label)}</span><strong>{html.escape(_text(value))}</strong></div>"


def _section_data(report: dict[str, Any], name: str) -> dict[str, Any]:
    """Return a domain section from both current and legacy report layouts."""
    value = report.get(name)
    if isinstance(value, dict):
        return value
    domain = report.get("domain")
    if isinstance(domain, dict) and isinstance(domain.get(name), dict):
        return domain[name]
    return {}


def _items(value: Any) -> list[Any]:
    if isinstance(value, list):
        return value
    if value in (None, "", {}, []):
        return []
    return [value]


def _value_list(value: Any) -> str:
    values = _items(value)
    return ", ".join(_text(item) for item in values) if values else "—"


def render(report: dict[str, Any], locale: str = "ru") -> str:
    """Return a concise, self-contained localized HTML report."""
    locale = normalize_locale(locale)
    text = {
        "en": {"lang": "en", "report": "intelligence report", "target": "target", "summary": "Summary", "pages": "Pages checked", "contacts": "Contacts", "external": "External resources", "redirects": "Redirect chain", "transitions": "Transitions", "final_url": "Final URL", "ports": "Open ports and technologies", "status": "Status", "open_ports": "Open ports", "details": "Contact information", "dns": "DNS records", "ip": "IP address information", "tls": "TLS overview", "whois": "WHOIS", "record_status": "Status", "records": "Records", "addresses": "Addresses", "address": "Primary address", "version": "IP version", "reverse_dns": "Reverse DNS", "organization": "Organization", "country": "Country", "city": "City", "region": "Region", "hostname": "Hostname", "timezone": "Timezone", "version_protocol": "Protocol", "cipher": "Cipher", "subject": "Subject", "issuer": "Issuer", "valid_from": "Valid from", "valid_to": "Valid to", "server": "Server", "registrar": "Registrar", "created": "Created", "updated": "Updated", "expires": "Expires", "name_servers": "Name servers", "privacy": "Privacy protection", "none": "Not found", "no_redirects": "No redirects", "no_ports": "No open ports found", "generated": "Generated by PhishIntel"},
        "ru": {"lang": "ru", "report": "отчёт разведки", "target": "цель", "summary": "Сводка", "pages": "Страниц проверено", "contacts": "Контакты", "external": "Внешние ресурсы", "redirects": "Цепочка перенаправлений", "transitions": "Переходов", "final_url": "Конечный URL", "ports": "Открытые порты и технологии", "status": "Статус", "open_ports": "Открытых портов", "details": "Контактная информация", "dns": "Записи DNS", "ip": "Информация об IP-адресе", "tls": "Краткая информация о TLS", "whois": "WHOIS", "record_status": "Статус", "records": "Записи", "addresses": "Адреса", "address": "Основной адрес", "version": "Версия IP", "reverse_dns": "Reverse DNS", "organization": "Организация", "country": "Страна", "city": "Город", "region": "Регион", "hostname": "Имя хоста", "timezone": "Часовой пояс", "version_protocol": "Протокол", "cipher": "Шифр", "subject": "Subject", "issuer": "Issuer", "valid_from": "Действителен с", "valid_to": "Действителен до", "server": "Сервер", "registrar": "Регистратор", "created": "Создан", "updated": "Обновлён", "expires": "Истекает", "name_servers": "DNS-серверы", "privacy": "Защита приватности", "none": "Не обнаружены", "no_redirects": "Переходов нет", "no_ports": "Открытые порты не обнаружены", "generated": "Сформировано PhishIntel"},
    }[locale]
    target = _text(report.get("target"))
    summary = report.get("summary", {})
    contacts = report.get("contacts", {})
    external = report.get("external_resources", {})
    port_scan = report.get("port_scan", {})
    dns_data = _section_data(report, "dns")
    ip_data = _section_data(report, "ip")
    tls_data = _section_data(report, "tls")
    whois_data = _section_data(report, "whois")
    redirects = report.get("redirects") or report.get("domain", {}).get("redirects", {})
    chain = redirects.get("chain", []) if isinstance(redirects, dict) else []
    contact_summary = "".join(
        f"<li><b>{html.escape(str(key))}</b>: {len(value) if isinstance(value, list) else html.escape(_text(value))}</li>"
        for key, value in contacts.items()
    ) or f"<li>{html.escape(text['none'])}</li>"
    contact_details = "".join(
        f"<li><b>{html.escape(str(key))}</b><ul>"
        f"{''.join(f'<li>{html.escape(_text(item))}</li>' for item in value) if isinstance(value, list) and value else f'<li>{html.escape(_text(value))}</li>'}"
        f"</ul></li>"
        for key, value in contacts.items()
    ) or f"<li>{html.escape(text['none'])}</li>"
    external_items = "".join(
        f"<li><b>{html.escape(str(key))}</b>: {len(value) if isinstance(value, list) else html.escape(_text(value))}</li>"
        for key, value in external.items()
    ) or f"<li>{html.escape(text['none'])}</li>"
    redirect_items = "".join(
        f"<li><code>{html.escape(_text(item.get('status_code')))}</code> "
        f"{html.escape(_text(item.get('from')))} → {html.escape(_text(item.get('to')))}</li>"
        for item in chain
    ) or f"<li>{html.escape(text['no_redirects'])}</li>"
    final_url = redirects.get("final_url") if isinstance(redirects, dict) else None
    port_items = "".join(
        "<li><code>{}/{}".format(
            html.escape(_text(item.get("port"))),
            html.escape(_text(item.get("protocol", "tcp"))),
        )
        + "</code> "
        + html.escape(_text(item.get("service") or "unknown"))
        + (" " + html.escape(_text(item.get("version"))) if item.get("version") else "")
        + (" — " + html.escape(_text(item.get("technology"))) if item.get("technology") else "")
        + "</li>"
        for item in port_scan.get("ports", [])
    ) or f"<li>{html.escape(text['no_ports'])}</li>"
    dns_items = "".join(
        f"<li><b>{html.escape(str(key).upper())}</b>: {html.escape(_value_list(value))}</li>"
        for key, value in dns_data.items()
        if key not in {"status", "error", "soa"} and value not in (None, "", [], {})
    ) or f"<li>{html.escape(text['none'])}</li>"
    ipinfo_data = ip_data.get("ipinfo") if isinstance(ip_data.get("ipinfo"), dict) else {}
    ip_rows = "".join(
        _row(text[label], ip_data.get(key))
        for key, label in (("status", "record_status"), ("address", "address"), ("addresses", "addresses"), ("version", "version"), ("reverse_dns", "reverse_dns"))
        if key in ip_data and ip_data.get(key) not in (None, "", [], {})
    )
    ip_rows += "".join(
        _row(text[label], ipinfo_data.get(key))
        for key, label in (("hostname", "hostname"), ("org", "organization"), ("country", "country"), ("region", "region"), ("city", "city"), ("timezone", "timezone"))
        if key in ipinfo_data and ipinfo_data.get(key) not in (None, "", [], {})
    )
    if not ip_rows:
        ip_rows = _row(text["record_status"], text["none"])
    tls_rows = "".join(
        _row(text[label], tls_data.get(key))
        for key, label in (("status", "record_status"), ("version", "version"), ("cipher", "cipher"), ("subject", "subject"), ("issuer", "issuer"), ("not_before", "valid_from"), ("not_after", "valid_to"))
        if key in tls_data
    ) or _row(text["record_status"], text["none"])
    whois_rows = "".join(
        _row(text[label], whois_data.get(key))
        for key, label in (("status", "record_status"), ("server", "server"), ("registrar", "registrar"), ("created", "created"), ("updated", "updated"), ("expires", "expires"), ("name_servers", "name_servers"), ("privacy", "privacy"))
        if key in whois_data
    ) or _row(text["record_status"], text["none"])

    return f"""<!doctype html>
<html lang="{text['lang']}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PhishIntel // {html.escape(target)}</title>
<style>
:root {{ color-scheme: dark; --bg:#07100d; --panel:#0d1b16; --line:#1d4d3a; --green:#39ff88; --muted:#8eb5a0; --red:#ff5874; }}
* {{ box-sizing:border-box; }} body {{ margin:0; background:radial-gradient(circle at top,#123126 0,#07100d 45%); color:#e2f5e8; font:16px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace; }}
main {{ max-width:1040px; margin:0 auto; padding:32px 18px 54px; }} header {{ border-bottom:1px solid var(--line); padding-bottom:20px; margin-bottom:20px; }}
h1 {{ color:var(--green); font-size:clamp(24px,5vw,42px); margin:0 0 8px; text-shadow:0 0 14px #39ff8855; }} h1::before {{ content:'> '; }} h2 {{ color:var(--green); font-size:19px; margin:0 0 14px; }}
.target {{ color:var(--muted); overflow-wrap:anywhere; }} .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(280px,1fr)); gap:16px; }}
section {{ background:#0d1b16dd; border:1px solid var(--line); border-radius:8px; padding:18px; margin-bottom:16px; box-shadow:0 0 22px #0008; }}
.row {{ display:flex; justify-content:space-between; gap:16px; border-bottom:1px dashed #276249; padding:7px 0; }} .row:last-child {{ border-bottom:0; }} .row span {{ color:var(--muted); }} strong {{ color:#fff; text-align:right; }}
ul {{ margin:0; padding-left:22px; }} li {{ margin:7px 0; overflow-wrap:anywhere; }} code {{ color:#101a13; background:var(--green); padding:1px 5px; border-radius:3px; }} .risk {{ color:var(--red); }} footer {{ color:var(--muted); font-size:12px; margin-top:28px; }}
</style>
</head>
<body><main>
<header><h1>PhishIntel // {text['report']}</h1><div class="target">{text['target']}: {html.escape(target)}</div></header>
<div class="grid">
<section><h2>{text['summary']}</h2>{_row(text['pages'], summary.get('pages_visited', '—'))}</section>
<section><h2>{text['contacts']}</h2><ul>{contact_summary}</ul></section>
<section><h2>{text['external']}</h2><ul>{external_items}</ul></section>
</div>
<section><h2>{text['redirects']}</h2>{_row(text['transitions'], redirects.get('count', len(chain)) if isinstance(redirects, dict) else 0)}{_row(text['final_url'], final_url)}<ul>{redirect_items}</ul></section>
<section><h2>{text['ports']}</h2>{_row(text['status'], port_scan.get('status', 'unavailable'))}{_row(text['open_ports'], port_scan.get('open_port_count', len(port_scan.get('ports', []))))}<ul>{port_items}</ul></section>
<div class="grid">
<section><h2>{text['ip']}</h2>{ip_rows}</section>
<section><h2>{text['dns']}</h2>{_row(text['record_status'], dns_data.get('status', text['none']))}<ul>{dns_items}</ul></section>
<section><h2>{text['tls']}</h2>{tls_rows}</section>
<section><h2>{text['whois']}</h2>{whois_rows}</section>
</div>
<section><h2>{text['details']}</h2><ul>{contact_details}</ul></section>
<footer>{text['generated']} • {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</footer>
</main></body></html>
"""


def save(report: dict[str, Any], output_dir: str | Path = "reports", locale: str = "ru") -> Path:
    path = report_path(report, output_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(report, locale=locale), encoding="utf-8")
    return path